version: '3.1'

services:
  bangkok:
    image: vvamzy/bangkok:latest
    deploy:
      replicas: 2
    networks:
      - swarm101

  munich:
    image: vvamzy/munich:latest
    deploy:
      replicas: 2
    networks:
      - swarm101

  tokyo:
    image: vvamzy/tokyo:latest
    deploy:
      replicas: 1
    networks:
      - swarm101

  nyc:
    image: vvamzy/nyc:latest
    deploy:
      replicas: 1
    networks:
      - swarm101

  front_gateway:
    image: vvamzy/front_gateway:latest
    deploy:
      replicas: 1
    ports:
      - 8000:8000
    networks:
      - swarm101

networks:
  swarm101:
    driver: overlay
    ipam:
      config:
        -
          subnet: 192.168.0.0/24
